// Mocks generated by Mockito 5.2.0 from annotations
// in pokemon/test/helpers/test_helper.dart.
// Do not manually edit this file.

import 'dart:async' as _i14;

import 'package:bloc/bloc.dart' as _i25;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pokemon/data/local/pokemon_cache_source.dart' as _i27;
import 'package:pokemon/data/mapper/pokemon_detail_mapper.dart' as _i24;
import 'package:pokemon/data/mapper/pokemon_entity_mapper.dart' as _i22;
import 'package:pokemon/data/model/pokemon_detail_cache.dart' as _i23;
import 'package:pokemon/data/model/pokemon_detail_response.dart' as _i13;
import 'package:pokemon/data/model/pokemons_response.dart' as _i12;
import 'package:pokemon/data/network/pokemon_remote_source.dart' as _i26;
import 'package:pokemon/domain/entities/app_error.dart' as _i15;
import 'package:pokemon/domain/entities/no_params.dart' as _i17;
import 'package:pokemon/domain/entities/pokemon_detail_entity.dart' as _i5;
import 'package:pokemon/domain/entities/pokemon_item_entity.dart' as _i16;
import 'package:pokemon/domain/repositories/pokemon_repository.dart' as _i2;
import 'package:pokemon/domain/usecases/favoritePokemon/add_favorite.dart'
    as _i6;
import 'package:pokemon/domain/usecases/favoritePokemon/check_if_pokemon_favorite.dart'
    as _i8;
import 'package:pokemon/domain/usecases/favoritePokemon/delete_favorite_pokemon.dart'
    as _i7;
import 'package:pokemon/domain/usecases/favoritePokemon/get_favorite_pokemons.dart'
    as _i10;
import 'package:pokemon/domain/usecases/fetchAll/fetch_all_pokemon.dart'
    as _i18;
import 'package:pokemon/domain/usecases/fetchPokemon/fetch_pokemon.dart'
    as _i19;
import 'package:pokemon/presentation/bloc/toggle_favorite/favorite_cubit.dart'
    as _i11;
import 'package:pokemon/presentation/mapper/detail_ui_mapper.dart' as _i21;
import 'package:pokemon/presentation/mapper/pokemon_ui_mapper.dart' as _i9;
import 'package:pokemon/presentation/models/pokemon_detail_ui.dart' as _i4;
import 'package:pokemon/presentation/models/pokemon_list_ui.dart' as _i20;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakePokemonRepository_0 extends _i1.Fake
    implements _i2.PokemonRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

class _FakeUiPokemonDetail_2 extends _i1.Fake implements _i4.UiPokemonDetail {}

class _FakePokemonDetailEntity_3 extends _i1.Fake
    implements _i5.PokemonDetailEntity {}

class _FakeAddFavorite_4 extends _i1.Fake implements _i6.AddFavorite {}

class _FakeDeleteFavoritePokemon_5 extends _i1.Fake
    implements _i7.DeleteFavoritePokemon {}

class _FakeCheckIfPokemonFav_6 extends _i1.Fake
    implements _i8.CheckIfPokemonFav {}

class _FakePokemonUiMapper_7 extends _i1.Fake implements _i9.PokemonUiMapper {}

class _FakeGetFavoritePokemons_8 extends _i1.Fake
    implements _i10.GetFavoritePokemons {}

class _FakeFavoriteState_9 extends _i1.Fake implements _i11.FavoriteState {}

class _FakePokemonsResponse_10 extends _i1.Fake
    implements _i12.PokemonsResponse {}

class _FakePokemonDetailResponse_11 extends _i1.Fake
    implements _i13.PokemonDetailResponse {}

/// A class which mocks [CheckIfPokemonFav].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckIfPokemonFav extends _i1.Mock implements _i8.CheckIfPokemonFav {
  MockCheckIfPokemonFav() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokemonRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakePokemonRepository_0()) as _i2.PokemonRepository);
  @override
  _i14.Future<_i3.Either<_i15.AppError, bool>> call(int? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i3.Either<_i15.AppError, bool>>.value(
                  _FakeEither_1<_i15.AppError, bool>()))
          as _i14.Future<_i3.Either<_i15.AppError, bool>>);
}

/// A class which mocks [GetFavoritePokemons].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFavoritePokemons extends _i1.Mock
    implements _i10.GetFavoritePokemons {
  MockGetFavoritePokemons() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokemonRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakePokemonRepository_0()) as _i2.PokemonRepository);
  @override
  _i14.Future<_i3.Either<_i15.AppError, List<_i16.PokemonItemEntity>>> call(
          _i17.NoParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<
                      _i3.Either<_i15.AppError,
                          List<_i16.PokemonItemEntity>>>.value(
                  _FakeEither_1<_i15.AppError, List<_i16.PokemonItemEntity>>()))
          as _i14.Future<_i3.Either<_i15.AppError, List<_i16.PokemonItemEntity>>>);
}

/// A class which mocks [AddFavorite].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddFavorite extends _i1.Mock implements _i6.AddFavorite {
  MockAddFavorite() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokemonRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakePokemonRepository_0()) as _i2.PokemonRepository);
  @override
  _i14.Future<_i3.Either<_i15.AppError, void>> call(
          _i5.PokemonDetailEntity? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i3.Either<_i15.AppError, void>>.value(
                  _FakeEither_1<_i15.AppError, void>()))
          as _i14.Future<_i3.Either<_i15.AppError, void>>);
}

/// A class which mocks [DeleteFavoritePokemon].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteFavoritePokemon extends _i1.Mock
    implements _i7.DeleteFavoritePokemon {
  MockDeleteFavoritePokemon() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokemonRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakePokemonRepository_0()) as _i2.PokemonRepository);
  @override
  _i14.Future<_i3.Either<_i15.AppError, void>> call(int? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i3.Either<_i15.AppError, void>>.value(
                  _FakeEither_1<_i15.AppError, void>()))
          as _i14.Future<_i3.Either<_i15.AppError, void>>);
}

/// A class which mocks [FetchAllPokemon].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchAllPokemon extends _i1.Mock implements _i18.FetchAllPokemon {
  MockFetchAllPokemon() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokemonRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakePokemonRepository_0()) as _i2.PokemonRepository);
  @override
  _i14.Future<_i3.Either<_i15.AppError, List<_i16.PokemonItemEntity>>> call(
          _i17.NoParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<
                      _i3.Either<_i15.AppError,
                          List<_i16.PokemonItemEntity>>>.value(
                  _FakeEither_1<_i15.AppError, List<_i16.PokemonItemEntity>>()))
          as _i14.Future<_i3.Either<_i15.AppError, List<_i16.PokemonItemEntity>>>);
}

/// A class which mocks [FetchPokemon].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchPokemon extends _i1.Mock implements _i19.FetchPokemon {
  MockFetchPokemon() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokemonRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakePokemonRepository_0()) as _i2.PokemonRepository);
  @override
  _i14.Future<_i3.Either<_i15.AppError, _i5.PokemonDetailEntity>> call(
          int? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<
                      _i3.Either<_i15.AppError, _i5.PokemonDetailEntity>>.value(
                  _FakeEither_1<_i15.AppError, _i5.PokemonDetailEntity>()))
          as _i14.Future<_i3.Either<_i15.AppError, _i5.PokemonDetailEntity>>);
}

/// A class which mocks [PokemonUiMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonUiMapper extends _i1.Mock implements _i9.PokemonUiMapper {
  MockPokemonUiMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i20.PokemonListUi> maps(List<_i16.PokemonItemEntity>? items) =>
      (super.noSuchMethod(Invocation.method(#maps, [items]),
          returnValue: <_i20.PokemonListUi>[]) as List<_i20.PokemonListUi>);
}

/// A class which mocks [DetailUiMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDetailUiMapper extends _i1.Mock implements _i21.DetailUiMapper {
  MockDetailUiMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.UiPokemonDetail mapItem(_i5.PokemonDetailEntity? entity) =>
      (super.noSuchMethod(Invocation.method(#mapItem, [entity]),
          returnValue: _FakeUiPokemonDetail_2()) as _i4.UiPokemonDetail);
}

/// A class which mocks [PokemonEntityMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonEntityMapper extends _i1.Mock
    implements _i22.PokemonEntityMapper {
  MockPokemonEntityMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i16.PokemonItemEntity> fromRemoteList(
          _i12.PokemonsResponse? response) =>
      (super.noSuchMethod(Invocation.method(#fromRemoteList, [response]),
              returnValue: <_i16.PokemonItemEntity>[])
          as List<_i16.PokemonItemEntity>);
  @override
  List<_i16.PokemonItemEntity> fromLocalList(
          List<_i23.PokemonDetailCache>? caches) =>
      (super.noSuchMethod(Invocation.method(#fromLocalList, [caches]),
              returnValue: <_i16.PokemonItemEntity>[])
          as List<_i16.PokemonItemEntity>);
}

/// A class which mocks [PokemonDetailMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonDetailMapper extends _i1.Mock
    implements _i24.PokemonDetailMapper {
  MockPokemonDetailMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.PokemonDetailEntity mapItem(_i13.PokemonDetailResponse? response) =>
      (super.noSuchMethod(Invocation.method(#mapItem, [response]),
              returnValue: _FakePokemonDetailEntity_3())
          as _i5.PokemonDetailEntity);
}

/// A class which mocks [FavoriteCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteCubit extends _i1.Mock implements _i11.FavoriteCubit {
  MockFavoriteCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.AddFavorite get addFavorite =>
      (super.noSuchMethod(Invocation.getter(#addFavorite),
          returnValue: _FakeAddFavorite_4()) as _i6.AddFavorite);
  @override
  _i7.DeleteFavoritePokemon get deleteFavorite =>
      (super.noSuchMethod(Invocation.getter(#deleteFavorite),
              returnValue: _FakeDeleteFavoritePokemon_5())
          as _i7.DeleteFavoritePokemon);
  @override
  _i8.CheckIfPokemonFav get checkIfPokemonFav =>
      (super.noSuchMethod(Invocation.getter(#checkIfPokemonFav),
          returnValue: _FakeCheckIfPokemonFav_6()) as _i8.CheckIfPokemonFav);
  @override
  _i9.PokemonUiMapper get uiMapper =>
      (super.noSuchMethod(Invocation.getter(#uiMapper),
          returnValue: _FakePokemonUiMapper_7()) as _i9.PokemonUiMapper);
  @override
  _i10.GetFavoritePokemons get getFavoritePokemons => (super.noSuchMethod(
      Invocation.getter(#getFavoritePokemons),
      returnValue: _FakeGetFavoritePokemons_8()) as _i10.GetFavoritePokemons);
  @override
  _i11.FavoriteState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _FakeFavoriteState_9()) as _i11.FavoriteState);
  @override
  _i14.Stream<_i11.FavoriteState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i11.FavoriteState>.empty())
          as _i14.Stream<_i11.FavoriteState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void toggleFavorite(_i4.UiPokemonDetail? model, bool? isFav) =>
      super.noSuchMethod(Invocation.method(#toggleFavorite, [model, isFav]),
          returnValueForMissingStub: null);
  @override
  void checkIsPokemonFavorite(int? id) =>
      super.noSuchMethod(Invocation.method(#checkIsPokemonFavorite, [id]),
          returnValueForMissingStub: null);
  @override
  void getFavorites() =>
      super.noSuchMethod(Invocation.method(#getFavorites, []),
          returnValueForMissingStub: null);
  @override
  void emit(_i11.FavoriteState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onChange(_i25.Change<_i11.FavoriteState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  _i14.Future<void> close() => (super.noSuchMethod(
      Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i14.Future<void>);
}

/// A class which mocks [PokemonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRepository extends _i1.Mock implements _i2.PokemonRepository {
  MockPokemonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i3.Either<_i15.AppError, List<_i16.PokemonItemEntity>>>
      getPokemons() => (super.noSuchMethod(Invocation.method(#getPokemons, []),
              returnValue: Future<
                      _i3.Either<_i15.AppError,
                          List<_i16.PokemonItemEntity>>>.value(
                  _FakeEither_1<_i15.AppError, List<_i16.PokemonItemEntity>>()))
          as _i14.Future<_i3.Either<_i15.AppError, List<_i16.PokemonItemEntity>>>);
  @override
  _i14.Future<_i3.Either<_i15.AppError, List<_i16.PokemonItemEntity>>>
      getFavoritePokemons() => (super.noSuchMethod(
          Invocation.method(#getFavoritePokemons, []),
          returnValue:
              Future<_i3.Either<_i15.AppError, List<_i16.PokemonItemEntity>>>.value(
                  _FakeEither_1<_i15.AppError,
                      List<_i16.PokemonItemEntity>>())) as _i14
          .Future<_i3.Either<_i15.AppError, List<_i16.PokemonItemEntity>>>);
  @override
  _i14.Future<_i3.Either<_i15.AppError, _i5.PokemonDetailEntity>> getPokemon(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getPokemon, [id]),
              returnValue: Future<
                      _i3.Either<_i15.AppError, _i5.PokemonDetailEntity>>.value(
                  _FakeEither_1<_i15.AppError, _i5.PokemonDetailEntity>()))
          as _i14.Future<_i3.Either<_i15.AppError, _i5.PokemonDetailEntity>>);
  @override
  _i14.Future<_i3.Either<_i15.AppError, void>> savePokemon(
          _i5.PokemonDetailEntity? entity) =>
      (super.noSuchMethod(Invocation.method(#savePokemon, [entity]),
              returnValue: Future<_i3.Either<_i15.AppError, void>>.value(
                  _FakeEither_1<_i15.AppError, void>()))
          as _i14.Future<_i3.Either<_i15.AppError, void>>);
  @override
  _i14.Future<_i3.Either<_i15.AppError, void>> deleteFavPokemon(int? id) =>
      (super.noSuchMethod(Invocation.method(#deleteFavPokemon, [id]),
              returnValue: Future<_i3.Either<_i15.AppError, void>>.value(
                  _FakeEither_1<_i15.AppError, void>()))
          as _i14.Future<_i3.Either<_i15.AppError, void>>);
  @override
  _i14.Future<_i3.Either<_i15.AppError, bool>> checkIfPokemonFav(int? id) =>
      (super.noSuchMethod(Invocation.method(#checkIfPokemonFav, [id]),
              returnValue: Future<_i3.Either<_i15.AppError, bool>>.value(
                  _FakeEither_1<_i15.AppError, bool>()))
          as _i14.Future<_i3.Either<_i15.AppError, bool>>);
}

/// A class which mocks [PokemonRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRemoteSource extends _i1.Mock
    implements _i26.PokemonRemoteSource {
  MockPokemonRemoteSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i12.PokemonsResponse> getPokemons() => (super.noSuchMethod(
          Invocation.method(#getPokemons, []),
          returnValue:
              Future<_i12.PokemonsResponse>.value(_FakePokemonsResponse_10()))
      as _i14.Future<_i12.PokemonsResponse>);
  @override
  _i14.Future<_i13.PokemonDetailResponse> getPokemonById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getPokemonById, [id]),
              returnValue: Future<_i13.PokemonDetailResponse>.value(
                  _FakePokemonDetailResponse_11()))
          as _i14.Future<_i13.PokemonDetailResponse>);
}

/// A class which mocks [PokemonCacheSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonCacheSource extends _i1.Mock
    implements _i27.PokemonCacheSource {
  MockPokemonCacheSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<List<_i23.PokemonDetailCache>> getPokemons() =>
      (super.noSuchMethod(Invocation.method(#getPokemons, []),
              returnValue: Future<List<_i23.PokemonDetailCache>>.value(
                  <_i23.PokemonDetailCache>[]))
          as _i14.Future<List<_i23.PokemonDetailCache>>);
  @override
  _i14.Future<void> savePokemonInCache(_i23.PokemonDetailCache? pokemon) =>
      (super.noSuchMethod(Invocation.method(#savePokemonInCache, [pokemon]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i14.Future<void>);
  @override
  _i14.Future<void> removePokemon(int? id) => (super.noSuchMethod(
      Invocation.method(#removePokemon, [id]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i14.Future<void>);
  @override
  _i14.Future<bool> checkIfFav(int? id) =>
      (super.noSuchMethod(Invocation.method(#checkIfFav, [id]),
          returnValue: Future<bool>.value(false)) as _i14.Future<bool>);
}
